version: 2

jobs:
  "elixir":
    docker:
      - image: elixir:1.5.2
        environment:
          MIX_ENV: test
          MESSENGER_PAGE_TOKEN: does_not_matter_in_test_env
          MESSENGER_PAGE_ID: also_does_not_matter_in_test_env
          MESSENGER_VERIFY_TOKEN: yup_like_the_previous_ones
      - image: postgres:9.4.1
        environment:
          POSTGRES_USER: ubuntu
    working_directory: ~/tbot
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar
      - run: mix deps.get
      - run: mix ecto.create
      - run: mix test

  "ruby":
    docker:
      - image: circleci/ruby:2.4
    working_directory: ~/tbot
    steps:
      - checkout
      - run: sudo apt-get install cmake
      - run: gem install pronto-credo --no-document
      - run: echo 'export PRONTO_PULL_REQUEST_ID=$CIRCLE_PR_NUMBER' >> $BASH_ENV
      - run: if [ $PRONTO_PULL_REQUEST_ID != false ]; then pronto run -f github_pr -c origin/master; fi

workflows:
  version: 2
  build:
    jobs:
      - elixir
      - ruby
